### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by xmha97** [Radiokot/osmand-display-app#5]
Hi,
Please publish a version on GitHub release page.
I need this app.
Thanks.

**Comment by Radiokot** [comment]
Hi Muhammad.
I will make a release tomorrow, but I'm wondering what you need the APK for 🤔

**Comment by xmha97** [comment]
> Hi Muhammad.
> I will make a release tomorrow, but I'm wondering what you need the APK for 🤔 

Thanks.

This app:
![212535953-71a9e10d-2c91-4f38-80ef-dce9b940366c.png](https://user-images.githubusercontent.com/23485114/232254356-12302f22-3f4e-4d99-abcb-5a780d825e32.png)

**Comment by Radiokot** [comment]
Here it is: https://github.com/Radiokot/osmand-display-app/releases/tag/1.0.0(1)

**Comment by xmha97** [comment]
Thanks.
