### ISSUE TITLE
Add monochrome icon 

### ISSUE THREAD

**Issue by xmha97** [Radiokot/osmand-display-app#6]
Please support the Android 13 Themed App Icons feature.

![Screenshot_2023-11-03-16-29-47-175_com.miui.home.jpg](https://github.com/Radiokot/osmand-display-app/assets/23485114/d58d9412-c668-4f91-bbda-fa62c4bc5bb5)

**Comment by Radiokot** [comment]
Do you use this app?

**Comment by xmha97** [comment]
> Do you use this app?

Not yet but I would like to build a device that can use this app.

**Comment by Radiokot** [comment]
Then I think the icon is not the first priority issue 😁 Good luck with building the display, hope you learn something new and get yourself a helpful device!

**Comment by xmha97** [comment]
> Then I think the icon is not the first priority issue 😁 Good luck with building the display, hope you learn something new and get yourself a helpful device!

😂
Yes, it is not the first priority, but it does not take much time to fix.

**Comment by Radiokot** [comment]
The icon is added in [1.3.0](https://github.com/Radiokot/osmand-display-app/releases/tag/1.3.0(4))

**Comment by xmha97** [comment]
Thanks 🙏
